version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    container_name: server
    restart: always
    env_file:
      - ./packages/server/.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:delegated
    networks:
      - server
    command: yarn run start:dev
    
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
     - POSTGRES_USER=$DB_USERNAME
     - POSTGRES_PASSWORD=$DB_PASSWORD
     - POSTGRES_DB=$DB_NAME
    volumes:
      - ./data:/data/postgres
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - server

networks:
  server:
    driver: bridge